const bdProducts = [{
        cod: "AE001",
        title: "Abercrombie & Fitch",
        image: "images/goods1.png",
        price: 65,
        categories: "men",
    },
    {
        cod: "HO001",
        title: "Hollister",
        image: "images/goods2.png",
        price: 40,
        categories: "men",
    },
    {
        cod: "HO002",
        title: "Hollister",
        image: "images/goods3.png",
        price: 45,
        categories: "women",
    },
    {
        cod: "AE002",
        title: "Abercrombie & Fitch",
        image: "images/goods4.png",
        price: 70,
        categories: "women",
    },
    {
        cod: "RA001",
        title: "Ralph Lauren",
        image: "images/goods5.png",
        price: 75,
        categories: "men",
    },
    {
        cod: "HO002",
        title: "Ralph Lauren",
        image: "images/goods6.png",
        price: 80,
        categories: "men",
    },
    //------------------------------------------------
    {
        cod: "AE001",
        title: "Abercrombie & Fitch",
        image: "images/tshirt_PNG7.png",
        price: 65,
        categories: "men",
    },
    {
        cod: "HO001",
        title: "Hollister",
        image: "images/tshirt_PNG8.png",
        price: 40,
        categories: "men",
    },
    {
        cod: "HO002",
        title: "Hollister",
        image: "images/tshirt_PNG9.png",
        price: 45,
        categories: "women",
    },
    {
        cod: "AE002",
        title: "Abercrombie & Fitch",
        image: "images/tshirt_PNG10.png",
        price: 70,
        categories: "women",
    },
    {
        cod: "RA001",
        title: "Ralph Lauren",
        image: "images/tshirt_PNG11.png",
        price: 75,
        categories: "men",
    },
    {
        cod: "HO002",
        title: "Ralph Lauren",
        image: "images/tshirt_PNG12.png",
        price: 80,
        categories: "men",
    },
    //------------------------------------------------
    {
        cod: "AE001",
        title: "Abercrombie & Fitch",
        image: "images/tshirt_PNG13.png",
        price: 65,
        categories: "men",
    },
    {
        cod: "HO001",
        title: "Hollister",
        image: "images/tshirt_PNG14.png",
        price: 40,
        categories: "men",
    },
    {
        cod: "HO002",
        title: "Hollister",
        image: "images/tshirt_PNG15.png",
        price: 45,
        categories: "women",
    },
    {
        cod: "AE002",
        title: "Abercrombie & Fitch",
        image: "images/tshirt_PNG16.png",
        price: 70,
        categories: "women",
    },
    {
        cod: "RA001",
        title: "Ralph Lauren",
        image: "images/tshirt_PNG17.png",
        price: 75,
        categories: "men",
    }
    ];